### ISSUE TITLE
Simplify CSS code for all shared properties.

### ISSUE THREAD

**Issue by josephtkim** [kyleweiler/prj-rev-bwfs-dasmoto#5]
It is usually a good idea to simplify the CSS code as much as possible, for shared properties. The font-weight property is also shared by multiple elements, so it would be a good idea to simplify the code like so

```css
h1, .block h2, .bluebold {
  font-weight: bold;
}
```
